import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './test.css'
import './animations.css'
import SidebarLayout1 from '@/components/sidebar-layouts/sidebar-layout-1'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-full relative`}>
        <SidebarLayout1>
          {children}
        </SidebarLayout1>
      </body>
    </html>
  )
}
